backup:
    build: .
    environment:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        S3_BUCKET_NAME: test
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./:/usr/src/app"
        - "/:/data"

